//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_root_cases_behavioral
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public string name_en { get; set; }
        public string name_fr { get; set; }
        public string name_es { get; set; }
        public int status_id { get; set; }
    }
}
