//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_case_routing
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public int company_secondary_type_id { get; set; }
        public int company_case_admin_department_id { get; set; }
        public int user_id { get; set; }
        public int scope_id { get; set; }
    }
}
