//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_case_routing_attachments
    {
        public int id { get; set; }
        public int company_case_routing_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string path_nm { get; set; }
        public string file_nm { get; set; }
        public string extension_nm { get; set; }
        public int user_id { get; set; }
        public System.DateTime upload_dt { get; set; }
    }
}
