//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_payments
    {
        public System.Guid id { get; set; }
        public int company_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public string cc_name { get; set; }
        public string cc_number { get; set; }
        public int cc_month { get; set; }
        public int cc_year { get; set; }
        public int cc_csv { get; set; }
        public decimal amount { get; set; }
        public string auth_code { get; set; }
        public Nullable<int> user_id { get; set; }
        public string local_invoice_number { get; set; }
    }
}
