//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_question_answer
    {
        public int id { get; set; }
        public int custom_question_id { get; set; }
        public int incident_id { get; set; }
        public string answer_text { get; set; }
        public int answer_value { get; set; }
    }
}
