//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class industry
    {
        public int id { get; set; }
        public string industry_name_en { get; set; }
        public string industry_name_fr { get; set; }
        public string industry_name_es { get; set; }
        public string industry_name_ru { get; set; }
        public string industry_name_ar { get; set; }
        public string code { get; set; }
    }
}
