//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_processed
    {
        public int id { get; set; }
        public int notification_id { get; set; }
        public string subs { get; set; }
        public string subject { get; set; }
        public string notification_text { get; set; }
        public string receivers { get; set; }
        public string cc { get; set; }
        public string bcc { get; set; }
        public bool is_processed { get; set; }
        public System.DateTime created_dt { get; set; }
    }
}
