//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class poster_industry_posters
    {
        public int id { get; set; }
        public int poster_id { get; set; }
        public int industry_posters_id { get; set; }
        public int status { get; set; }
    }
}
