//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_owner
    {
        public int id { get; set; }
        public int report_id { get; set; }
        public int user_id { get; set; }
        public bool active_flag { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
