//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class resolution
    {
        public int id { get; set; }
        public string resolution_en { get; set; }
        public string resolution_fr { get; set; }
        public string resolution_es { get; set; }
        public string resolution_ru { get; set; }
        public string resolution_ja { get; set; }
        public string description { get; set; }
    }
}
