//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public int id { get; set; }
        public string source_en { get; set; }
        public string source_fr { get; set; }
        public string source_es { get; set; }
        public string source_ru { get; set; }
        public string source_ar { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
        public string code { get; set; }
    }
}
