//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_raph_client
    {
        public int client_id { get; set; }
        public string client_nm { get; set; }
        public int company_id { get; set; }
        public string company_nm { get; set; }
        public Nullable<System.DateTime> registration_dt { get; set; }
        public int user_id { get; set; }
        public string user_nm { get; set; }
        public string login_nm { get; set; }
    }
}
