//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public int id { get; set; }
        public string type_en { get; set; }
        public string type_fr { get; set; }
        public string type_es { get; set; }
        public string type_ru { get; set; }
        public string type_ar { get; set; }
        public string type_jp { get; set; }
        public string code { get; set; }
    }
}
