//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzbilling_info
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int address_id { get; set; }
        public Nullable<int> billing_option_id { get; set; }
        public int status_id { get; set; }
        public string billing_info_nm { get; set; }
        public string business_type_nm { get; set; }
        public string principle_nm { get; set; }
        public string contact_nm { get; set; }
        public string email { get; set; }
        public string bank_nm { get; set; }
        public string bank_work_no { get; set; }
        public string branch_nm { get; set; }
        public string reference_nm { get; set; }
        public string reference_work_no { get; set; }
        public int credit_level_id { get; set; }
        public string card_no { get; set; }
        public string verify_no { get; set; }
        public string expiry_dt { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    }
}
