//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzcase_type
    {
        public int id { get; set; }
        public int status_id { get; set; }
        public int negative_in { get; set; }
        public string case_type_nm { get; set; }
        public string case_type_nf { get; set; }
        public string case_type_ns { get; set; }
        public string case_type_nr { get; set; }
        public string case_type_na { get; set; }
        public string case_type_nj { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    }
}
