//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzmediator_secondary_type
    {
        public int id { get; set; }
        public Nullable<int> client_int { get; set; }
        public Nullable<int> company_id { get; set; }
        public int mediator_id { get; set; }
        public int secondary_type_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    }
}
