//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzzzreport_message_attachment
    {
        public int id { get; set; }
        public int report_message_id { get; set; }
        public string path_nm { get; set; }
        public string file_nm { get; set; }
        public string file_extension_nm { get; set; }
        public byte[] file_stream { get; set; }
        public int status_id { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    }
}
