using System;
using System.Runtime.Serialization;
using EC.Constants;

namespace EC.Service.DTO
{
    /// <summary>
    /// This DTO corresponds to the model class IBasicChannelAudit. It holds information
    /// common to audit records generated by any notification channel.
    /// </summary>
    
    [DataContract]
    [KnownType(typeof(EmailChannelAudit))]

    public class BasicChannelAudit : Audit
    {
        /// <summary>
        /// Name of the channel with which the message has been sent.
        /// </summary>

        [DataMember]
        public string ChannelName { get; set; }

        /// <summary>
        /// User Id of the user this notification is meant for.
        /// </summary>

        [DataMember]
        public Guid NotificationUserId { get; set; }

        /// <summary>
        /// Queue item Id.
        /// </summary>

        [DataMember]
        public Guid NotificationChannelQueueItemId { get; set; }

        /// <summary>
        /// Notification Id which resulted into this message.
        /// </summary>

        [DataMember]
        public Guid NotificationId { get; set; }

        /// <summary>
        /// Receiver Id of the sent message.
        /// </summary>

        [DataMember]
        public Guid NotificationReceiverId { get; set; }

        /// <summary>
        /// Category of the notification.
        /// </summary>

        [DataMember]
        public NotificationCategoriesEnum Category { get; set; }

        /// <summary>
        /// Sub-category of the notification.
        /// </summary>

        [DataMember]
        public NotificationSubCategoriesEnum SubCategory { get; set; }

        /// <summary>
        /// Notification priority.
        /// </summary>

        [DataMember]
        public NotificationPrioritiesEnum Priority { get; set; }

        /// <summary>
        /// cshtml file name (without extension) containing the full message which should be sent.
        /// </summary>

        [DataMember]
        public string TemplateName { get; set; }
    }
}
