//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_secondary_type
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> parent_secondary_type { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string secondary_type_en { get; set; }
        public string secondary_type_fr { get; set; }
        public string secondary_type_es { get; set; }
        public string secondary_type_ru { get; set; }
        public string secondary_type_ar { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
        public string description_en { get; set; }
        public string description_fr { get; set; }
        public string description_de { get; set; }
        public string description_ru { get; set; }
        public string description_ar { get; set; }
        public string description_jp { get; set; }
        public string description_es { get; set; }
    }
}
