//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_third_level_type
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public int company_id { get; set; }
        public Nullable<int> secondary_type_id { get; set; }
        public string third_level_type_name_en { get; set; }
        public string third_level_type_name_fr { get; set; }
        public string third_level_type_name_es { get; set; }
        public int status_id { get; set; }
    }
}
