//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_posters
    {
        public int id { get; set; }
        public int status { get; set; }
        public string message_posters_en { get; set; }
        public string message_posters_fr { get; set; }
        public string message_posters_es { get; set; }
    }
}
