//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ongoing
    {
        public int id { get; set; }
        public string ongoing_en { get; set; }
        public string ongoing_fr { get; set; }
        public string ongoing_ru { get; set; }
        public string ongoing_ar { get; set; }
        public string ongoing_es { get; set; }
        public string ongoing_ja { get; set; }
        public string code { get; set; }
    }
}
