//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_change_password
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string password_token { get; set; }
        public System.DateTime created_on { get; set; }
        public string user_ip { get; set; }
        public int password_updated { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string updated_user_ip { get; set; }
    }
}
