//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Framework.TimeZone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EC.Framework.TimeZone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Tzs&gt;
        ///&lt;Tz dn=&quot;(GMT-12:00) International Date Line West&quot; sn=&quot;Dateline Standard Time&quot; dln=&quot;Dateline Daylight Time&quot; bias=&quot;720&quot; sbias=&quot;0&quot; dlbias=&quot;-60&quot; ddate=&quot;0,0,0,0,0,0,0,0&quot; sdate=&quot;0,0,0,0,0,0,0,0&quot; idx=&quot;0&quot; /&gt;
        ///&lt;Tz dn=&quot;(GMT-11:00) Midway Island, Samoa&quot; sn=&quot;Samoa Standard Time&quot; dln=&quot;Samoa Daylight Time&quot; bias=&quot;660&quot; sbias=&quot;0&quot; dlbias=&quot;-60&quot; ddate=&quot;0,0,0,0,0,0,0,0&quot; sdate=&quot;0,0,0,0,0,0,0,0&quot; idx=&quot;1&quot; /&gt;
        ///&lt;Tz dn=&quot;(GMT-10:00) Hawaii&quot; sn=&quot;Hawaiian Standard Time&quot; dln=&quot;Hawaiian Daylight Time&quot; bias=&quot;600&quot; sbias=&quot;0&quot; dlbias=&quot;-60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tzs {
            get {
                return ResourceManager.GetString("Tzs", resourceCulture);
            }
        }
    }
}
