//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int id { get; set; }
        public string description_en { get; set; }
        public string description_fr { get; set; }
        public string description_ru { get; set; }
        public string desciption_es { get; set; }
        public string code { get; set; }
        public bool reporter_visible { get; set; }
        public string icon_path { get; set; }
    }
}
