//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.companies = new HashSet<company>();
        }
    
        public int id { get; set; }
        public int province_id { get; set; }
        public string address_line1_ds { get; set; }
        public string address_line2_ds { get; set; }
        public string city_nm { get; set; }
        public string postal_code_cl { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string work_phone { get; set; }
        public string cell_phone { get; set; }
        public string fax_no { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual ICollection<company> companies { get; set; }
    }
}
