//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_invitation
    {
        public int id { get; set; }
        public string invitation_code { get; set; }
        public int created_by_company_id { get; set; }
        public int created_by_user_id { get; set; }
        public System.DateTime created_dt { get; set; }
        public int is_active { get; set; }
        public string comments { get; set; }
    }
}
