//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class demoq_request
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_contact { get; set; }
        public string user_company { get; set; }
        public string user_role { get; set; }
        public string user_comment { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    }
}
