//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class injury_damage
    {
        public int id { get; set; }
        public string text_en { get; set; }
        public string text_fr { get; set; }
        public string text_es { get; set; }
        public string text_ru { get; set; }
        public string text_ar { get; set; }
        public string code { get; set; }
    }
}
