//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class investigation_status
    {
        public int id { get; set; }
        public string investigation_status_en { get; set; }
        public string investigation_status_fr { get; set; }
        public string investigation_status_es { get; set; }
        public string investigation_status_ru { get; set; }
        public string investigation_status_ja { get; set; }
    }
}
