//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_history
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string ip { get; set; }
        public string login_nm { get; set; }
        public int success_in { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public string browser_name { get; set; }
        public string browser_version { get; set; }
    }
}
