//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_summary_period
    {
        public int id { get; set; }
        public int notification_period_value { get; set; }
        public string notification_period_en { get; set; }
        public string notification_period_fr { get; set; }
        public string notification_period_ru { get; set; }
        public string notification_period_es { get; set; }
        public string notification_period_ar { get; set; }
        public string code { get; set; }
    }
}
