//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesExternalEmail.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        public int id { get; set; }
        public int country_id { get; set; }
        public string province_cl { get; set; }
        public string province_nm { get; set; }
        public string province_nf { get; set; }
        public string province_ns { get; set; }
        public string province_nr { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
    }
}
