//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class anonymity
    {
        public int id { get; set; }
        public string anonymity_en { get; set; }
        public string anonymity_en_company { get; set; }
        public string anonymity_fr { get; set; }
        public string anonymity_fr_company { get; set; }
        public string anonymity_es { get; set; }
        public string anonymity_es_company { get; set; }
        public string anonymity_ru { get; set; }
        public string anonymity_ru_company { get; set; }
        public string anonymity_ar { get; set; }
        public string anonymity_ar_company { get; set; }
        public string anonymity_ds_en { get; set; }
        public string anonymity_ds_fr { get; set; }
        public string anonymity_ds_es { get; set; }
        public string anonymity_ds_ru { get; set; }
        public string anonymity_ds_ar { get; set; }
        public System.DateTime last_update_dt { get; set; }
        public int user_id { get; set; }
        public string code { get; set; }
        public string anonymity_company_es { get; set; }
        public string anonymity_company_fr { get; set; }
        public string anonymity_company_ar { get; set; }
        public string anonymity_company_ru { get; set; }
        public string anonymity_company_en { get; set; }
    }
}
