//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_closure_reason
    {
        public int id { get; set; }
        public string case_closure_reason_en { get; set; }
        public string case_closure_reason_fr { get; set; }
        public string case_closure_reason_es { get; set; }
        public string case_closure_reason_ru { get; set; }
        public string case_closure_reason_jp { get; set; }
        public string case_closure_reason_ar { get; set; }
        public int status_id { get; set; }
        public int user_id { get; set; }
    }
}
