//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class frequency
    {
        public int id { get; set; }
        public string description_en { get; set; }
        public string description_fr { get; set; }
        public string description_es { get; set; }
        public string description_ru { get; set; }
        public string description_ar { get; set; }
        public string code { get; set; }
    }
}
