//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitation
    {
        public int id { get; set; }
        public string email { get; set; }
        public string code { get; set; }
        public int sent_by_user_id { get; set; }
        public System.DateTime created_on { get; set; }
        public int used_flag { get; set; }
        public Nullable<System.DateTime> used_on { get; set; }
        public string comment { get; set; }
    }
}
