//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public int report_id { get; set; }
        public string subject_ds { get; set; }
        public string body_tx { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public int reporter_access { get; set; }
        public int sender_id { get; set; }
        public string ip_ds { get; set; }
        public Nullable<int> sent_to_id { get; set; }
    }
}
