//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_log
    {
        public int id { get; set; }
        public int report_id { get; set; }
        public System.DateTime created_dt { get; set; }
        public string action_ds { get; set; }
        public int user_id { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<int> second_user_id { get; set; }
        public string string_to_add { get; set; }
    }
}
