//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Data.Models.ECDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_in_report
    {
        public int id { get; set; }
        public string role_en { get; set; }
        public string role_fr { get; set; }
        public string role_ru { get; set; }
        public string role_es { get; set; }
        public string role_ar { get; set; }
    }
}
